name: Build & Publish app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
      - name: version increase
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch --force -m "Version %s"
          git push
          git push --tags
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: dist/
          BUILD_SCRIPT: npm install && npm run build:prod
